apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-gcs-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Pi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: perf
    name: gcp-gcs-csi-static-pvc
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <your gcs bucket> # unique bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-gcs-csi-static-pvc
  namespace: perf
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  volumeName: gcp-gcs-csi-pv
  storageClassName: dummy-storage-class