apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-perf-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    # This is a placeholder, can be any number. It needs to match with the PVC resource.requests.storage field
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  mountOptions:
  - stat-cache-capacity=20000
  - stat-cache-ttl=120m0s
  - type-cache-ttl=120m0s
  claimRef:
    namespace: perf
    name: ml-perf-pvc
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <your gcs bucket> # unique bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-perf-pvc
  namespace: perf
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ml-perf-pv
  storageClassName: dummy-storage-class