kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: daos-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: daos-pv
  resources:
    requests:
      storage: 12Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: daos-pv
spec:
  storageClassName: ""
  capacity:
    storage: 12Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: parallelstore.csi.storage.gke.io
    volumeHandle: <pool-name>/<container-name>
    volumeAttributes:
      ip: <access-points>
      network: <network-name>