apiVersion: batch/v1
kind: Job
metadata:
  name: dlio-job
  namespace: perf
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: dlio-job
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "48"
        gke-gcsfuse/memory-limit: "20Gi"
        gke-gcsfuse/ephemeral-storage-limit: "20Gi"
    spec:
      containers:
      - name: dlio
        image: zhenghh04/dlio:mlperf_storage_v0.5.1_amd64
        resources:
          limits:
            cpu: 48
            memory: 780Gi
        command: [ "/bin/sh", "-c" ]
        args: [ "<your command>" ]
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: ml-perf-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      serviceAccountName: ml-perf-ksa
      volumes:
      - name: ml-perf-volume
        persistentVolumeClaim:
          claimName: ml-perf-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: Never