apiVersion: batch/v1
kind: Job
metadata:
  name: dlio-job
  namespace: perf
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: dlio-job
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "500m"
        gke-gcsfuse/memory-limit: "30Gi"
        gke-gcsfuse/ephemeral-storage-limit: "30Gi"
    spec:
      containers:
      - name: dlio
        image: zhenghh04/dlio:mlperf_storage_v0.5.1_amd64
        resources:
          limits:
            cpu: 2
            memory: 128Gi
        command: [ "/bin/sh", "-c" ]
        args: [ "<your command>" ]
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      serviceAccountName: ml-perf-ksa
      volumes:
      - name: gcp-gcs-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-gcs-csi-static-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: Never
