apiVersion: v1
kind: Namespace
metadata:
  name: example
---
# Tensorflow/Jupyter StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tensorflow
  namespace: example
spec:
  selector:
    matchLabels:
      pod: tensorflow-pod
  serviceName: tensorflow
  replicas: 1
  template:
    metadata:
      labels:
        pod: tensorflow-pod
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        # cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 30
      containers:
      - name: tensorflow-container
        image: tensorflow/tensorflow:2.13.0-gpu-jupyter
        volumeMounts:
        - name: tensorflow-pvc
          mountPath: /tf/saved
        resources:
            limits:
              nvidia.com/gpu: "1"
              ephemeral-storage: 30Gi
              memory: 30Gi
            requests:
              nvidia.com/gpu: "1"
              ephemeral-storage: 30Gi
              memory: 30Gi
      volumes:
        - name: tensorflow-pvc
          persistentVolumeClaim:
            claimName: tensorflow-pvc
## Optional: override and set your own token
#        env:
#          - name: JUPYTER_TOKEN
#            value: "jupyter"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-pvc
  namespace: example
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: tensorflow-pv
  resources:
    requests:
      storage: 9Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tensorflow-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: ""
  capacity:
    storage: 9Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/us-central1-c/test-hs1/vol"
    volumeAttributes:
      ip: 10.210.242.194 # Modify this to Pre-provisioned Filestore instance IP
      volume: vol # Modify this to Pre-provisioned Filestore instance share name
---
# Headless service for the above StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: tensorflow
spec:
  ports:
  - port: 8888
  clusterIP: None
  selector:
    pod: tensorflow-pod
---
# External service
apiVersion: "v1"
kind: "Service"
metadata:
  name: tensorflow-jupyter
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8888
  selector:
    pod: tensorflow-pod
  type: LoadBalancer
